# Generated by Django 5.2.17 on 2026-10-07 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('score', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territories', to='games.game')),
                ('neighbors', models.ManyToManyField(blank=True, to='games.territory')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='territories', to='games.player')),
            ],
        ),
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health', models.IntegerField(default=3)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capital', to='games.player')),
                ('territory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capital', to='games.territory')),
            ],
        ),
        migrations.AddConstraint(
            model_name='territory',
            constraint=models.UniqueConstraint(fields=('game', 'name'), name='unique_territory_name_per_game'),
        ),
        migrations.AddConstraint(
            model_name='territory',
            constraint=models.UniqueConstraint(fields=('game', 'slug'), name='unique_territory_slug_per_game'),
        ),
        migrations.AddConstraint(
            model_name='territory',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0)), name='territory_score_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='capital',
            constraint=models.CheckConstraint(condition=models.Q(('health__gte', 0), ('health__lte', 3)), name='capital_health_between_0_and_3'),
        ),
    ]
